logging:
  level:
    cn.tedu: debug

server:
  port: 7071

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/charging?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: orderService
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual  # 手动确认消息
    #开启确认模式 用来确认RabbitMQ成功收到消息
    publisher-confirm-type: correlated

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml