logging:
  level:
    cn.tedu: debug

server:
  port: 7071

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/charging?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: orderService
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml